# Generated by Django 6.0.3 on 2026-04-03 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_conversationmessage_directmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='channel',
            new_name='message_type',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='scheduled_at',
            new_name='scheduled_for',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='shop',
            new_name='shop_profile',
        ),
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='shop',
            new_name='shop_profile',
        ),
        migrations.RemoveField(
            model_name='message',
            name='failed_deliveries',
        ),
        migrations.RemoveField(
            model_name='message',
            name='successful_deliveries',
        ),
        migrations.RemoveField(
            model_name='message',
            name='total_recipients',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='category',
            field=models.CharField(choices=[('new_arrivals', 'New Arrivals'), ('sale_alert', 'Sale Alert'), ('promotional', 'Promotional'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sent', models.IntegerField(default=0)),
                ('successful', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('delivery_timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_report', to='messaging.message')),
            ],
        ),
    ]
