# Generated by Django 6.0.3 on 2026-04-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
